all:
  children:
    servers:
      hosts:
        localhost:
          ansible_host: 127.0.0.1
          ansible_ssh_private_key_file: '{{ lookup(''ansible.builtin.env'', ''HOME'')
            }}/.ssh/id_ed25519'

